server:
    port : 8080
spring :
    application :
        name : customer
        datasource:
            driver-class-name: org.postgresql.Driver
#            driverClassName: org.postgresql.Driver
            username: 'amigoscode'
            url: jdbc:postgresql://localhost:5435/user
            password: 'password'
            jpa:
                database: POSTGRESQL
                properties:
                    hibernate:
                        dialect: org.hibernate.dialect.PostgreSQLDialect
                        format_sql: 'true'
                hibernate:
                    ddl-auto: update
                show-sql: 'true'
    profiles:
        active: dev
