
#server:
#port : 8080
#
#Spring :
#    application :
#        name = customer
    #    datasource:
    #        username: 'microserviceexample'
    #        url: jdbc:postgresql://localhost:5432/customer
    #        password: 'password'
    #        jpa:
    #            properties:
    #                hibernate:
    #                    dialect: org.hibernate.dialet.PostgreSQLDialect
    #                    format_sql: 'true'
    #            hibernate:
    #                ddl-auto: update
    #            show-sql: 'true'
