#services :
#    postgres :
#        container_name : postgres
#        image : postgres
#        enviroment :
#            POSTGRES_USER  : postgres
#            POSTGRES_PASSWORD : admin
#            PGDATA : /data/postgres
#        volumes :
#            - postgres:/data/postgres
#        ports:
#            "5432:5432"
#        networks:
#            - postgres
#        restart : unless-stopped
#
#    pgadmin :
#        container_name: pgadmin
#        image : dpage/pgadmin4
#        environment :
#            PGADMIN_DEFAULT_EMAIL : ${PGADMIN_DEFAULT_EMAIL:-pgadmin4}
#            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin4}
#            PGADMIN_CONFIG_SERVER_MODE : 'False'
#        volumes:
#         - pgadmin:/var/lib/pgadmin
#        posts :
#            - "5050:80"
#        networks :
#            - postgres
#        restart : unless-stopped
#
#        networks :
#            postgres:
#            driver : bridge
#
#        volumes :
#            postgres :
#            pgadmin :